#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x2209D6902F969C95 (meissner@suse.de)
#
Name     : libmtp
Version  : 1.1.14
Release  : 2
URL      : https://downloads.sourceforge.net/project/libmtp/libmtp/1.1.14/libmtp-1.1.14.tar.gz
Source0  : https://downloads.sourceforge.net/project/libmtp/libmtp/1.1.14/libmtp-1.1.14.tar.gz
Source99 : https://downloads.sourceforge.net/project/libmtp/libmtp/1.1.14/libmtp-1.1.14.tar.gz.asc
Summary  : libmtp is a library for accessing Media Transfer Protocol devices
Group    : Development/Tools
License  : LGPL-2.1
Requires: libmtp-bin
Requires: libmtp-config
Requires: libmtp-lib
BuildRequires : pkgconfig(libusb-1.0)

%description
Building and Installing
-----------------------
See the "INSTALL" file.
Initiator and Responder
-----------------------

%package bin
Summary: bin components for the libmtp package.
Group: Binaries
Requires: libmtp-config

%description bin
bin components for the libmtp package.


%package config
Summary: config components for the libmtp package.
Group: Default

%description config
config components for the libmtp package.


%package dev
Summary: dev components for the libmtp package.
Group: Development
Requires: libmtp-lib
Requires: libmtp-bin
Provides: libmtp-devel

%description dev
dev components for the libmtp package.


%package lib
Summary: lib components for the libmtp package.
Group: Libraries

%description lib
lib components for the libmtp package.


%prep
%setup -q -n libmtp-1.1.14

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1510947362
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1510947362
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
/usr/lib/udev/hwdb.d/69-libmtp.hwdb
/usr/lib/udev/mtp-probe

%files bin
%defattr(-,root,root,-)
/usr/bin/mtp-albumart
/usr/bin/mtp-albums
/usr/bin/mtp-connect
/usr/bin/mtp-delfile
/usr/bin/mtp-detect
/usr/bin/mtp-emptyfolders
/usr/bin/mtp-files
/usr/bin/mtp-filetree
/usr/bin/mtp-folders
/usr/bin/mtp-format
/usr/bin/mtp-getfile
/usr/bin/mtp-getplaylist
/usr/bin/mtp-hotplug
/usr/bin/mtp-newfolder
/usr/bin/mtp-newplaylist
/usr/bin/mtp-playlists
/usr/bin/mtp-reset
/usr/bin/mtp-sendfile
/usr/bin/mtp-sendtr
/usr/bin/mtp-thumb
/usr/bin/mtp-tracks
/usr/bin/mtp-trexist

%files config
%defattr(-,root,root,-)
/usr/lib/udev/rules.d/69-libmtp.rules

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libmtp.so
/usr/lib64/pkgconfig/libmtp.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libmtp.so.9
/usr/lib64/libmtp.so.9.3.0
